/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MobileId = IDL.Nat;
export const RouteInput = IDL.Record({
  'serviceType' : IDL.Text,
  'mobileId' : MobileId,
  'officialName' : IDL.Text,
});
export const RouteId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Minutes = IDL.Float64;
export const Kilometers = IDL.Float64;
export const RouteView = IDL.Record({
  'id' : RouteId,
  'serviceType' : IDL.Text,
  'startedAt' : Timestamp,
  'endedAt' : IDL.Opt(Timestamp),
  'mobileId' : MobileId,
  'officialName' : IDL.Text,
  'durationMinutes' : IDL.Opt(Minutes),
  'totalKilometers' : Kilometers,
});
export const Domicilio = IDL.Record({
  'arrivalTime' : IDL.Text,
  'departureTime' : IDL.Text,
  'timeAtDomicile' : Minutes,
  'address' : IDL.Text,
});
export const ServiceInput = IDL.Record({
  'kmStart' : Kilometers,
  'domicilios' : IDL.Vec(Domicilio),
  'waitMinutes' : Minutes,
  'officialName' : IDL.Text,
  'tagCount' : IDL.Nat,
  'kmEnd' : Kilometers,
});
export const Pesos = IDL.Nat;
export const ServiceBreakdown = IDL.Record({
  'total' : Pesos,
  'kilometros' : Kilometers,
  'minutos' : Minutes,
  'importeTag' : Pesos,
  'cantidadTag' : IDL.Nat,
  'bajadaDeBandera' : Pesos,
  'importeKilometros' : Pesos,
  'importeTiempo' : Pesos,
});
export const MobileInput = IDL.Record({
  'serviceType' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'officialName' : IDL.Text,
  'mobileIdentifier' : IDL.Text,
});
export const MobileStatus = IDL.Variant({
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const MobileView = IDL.Record({
  'id' : MobileId,
  'status' : MobileStatus,
  'serviceType' : IDL.Text,
  'username' : IDL.Text,
  'lastUpdate' : IDL.Opt(Timestamp),
  'officialName' : IDL.Text,
  'lastLatitude' : IDL.Opt(IDL.Float64),
  'lastLongitude' : IDL.Opt(IDL.Float64),
  'mobileIdentifier' : IDL.Text,
});
export const ServiceId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const MobilePositionView = IDL.Record({
  'id' : MobileId,
  'status' : MobileStatus,
  'latitude' : IDL.Opt(IDL.Float64),
  'lastUpdate' : IDL.Opt(Timestamp),
  'officialName' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
  'mobileIdentifier' : IDL.Text,
});
export const Rates = IDL.Record({
  'porMinuto' : Pesos,
  'porKilometro' : Pesos,
  'bajadaDeBandera' : Pesos,
  'porTag' : Pesos,
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'kmStart' : Kilometers,
  'total' : Pesos,
  'owner' : IDL.Principal,
  'breakdown' : ServiceBreakdown,
  'createdAt' : Timestamp,
  'domicilios' : IDL.Vec(Domicilio),
  'waitMinutes' : Minutes,
  'officialName' : IDL.Text,
  'kmTraveled' : Kilometers,
  'tagCount' : IDL.Nat,
  'kmEnd' : Kilometers,
});
export const RouteFilter = IDL.Record({
  'to' : IDL.Opt(Timestamp),
  'from' : IDL.Opt(Timestamp),
  'mobileId' : IDL.Opt(MobileId),
});
export const ServiceSummary = IDL.Record({
  'id' : ServiceId,
  'total' : Pesos,
  'createdAt' : Timestamp,
  'minutes' : Minutes,
  'officialName' : IDL.Text,
  'kmTraveled' : Kilometers,
});
export const Position = IDL.Record({
  'latitude' : IDL.Float64,
  'recordedAt' : Timestamp,
  'longitude' : IDL.Float64,
});
export const MobileUpdate = IDL.Record({
  'serviceType' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Opt(IDL.Text),
  'officialName' : IDL.Text,
  'mobileIdentifier' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRoute' : IDL.Func([RouteInput], [RouteView], []),
  'calculateService' : IDL.Func([ServiceInput], [ServiceBreakdown], ['query']),
  'createMobile' : IDL.Func([MobileInput], [MobileView], []),
  'deleteMobile' : IDL.Func([MobileId], [], []),
  'deleteService' : IDL.Func([ServiceId], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerMobile' : IDL.Func([], [IDL.Opt(MobileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMobile' : IDL.Func([MobileId], [IDL.Opt(MobileView)], ['query']),
  'getMobilePosition' : IDL.Func(
      [MobileId],
      [IDL.Opt(MobilePositionView)],
      ['query'],
    ),
  'getRates' : IDL.Func([], [Rates], ['query']),
  'getRoute' : IDL.Func([RouteId], [IDL.Opt(RouteView)], ['query']),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkMobilePrincipal' : IDL.Func([IDL.Text, IDL.Text], [MobileView], []),
  'listMobilePositions' : IDL.Func(
      [],
      [IDL.Vec(MobilePositionView)],
      ['query'],
    ),
  'listMobiles' : IDL.Func([], [IDL.Vec(MobileView)], ['query']),
  'listRoutes' : IDL.Func([RouteFilter], [IDL.Vec(RouteView)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(ServiceSummary)], ['query']),
  'registerPosition' : IDL.Func([IDL.Float64, IDL.Float64], [Position], []),
  'saveService' : IDL.Func([ServiceInput], [Service], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateMobile' : IDL.Func([MobileId, MobileUpdate], [MobileView], []),
  'updateRates' : IDL.Func([Rates], [Rates], []),
  'updateService' : IDL.Func([ServiceId, ServiceInput], [Service], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MobileId = IDL.Nat;
  const RouteInput = IDL.Record({
    'serviceType' : IDL.Text,
    'mobileId' : MobileId,
    'officialName' : IDL.Text,
  });
  const RouteId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Minutes = IDL.Float64;
  const Kilometers = IDL.Float64;
  const RouteView = IDL.Record({
    'id' : RouteId,
    'serviceType' : IDL.Text,
    'startedAt' : Timestamp,
    'endedAt' : IDL.Opt(Timestamp),
    'mobileId' : MobileId,
    'officialName' : IDL.Text,
    'durationMinutes' : IDL.Opt(Minutes),
    'totalKilometers' : Kilometers,
  });
  const Domicilio = IDL.Record({
    'arrivalTime' : IDL.Text,
    'departureTime' : IDL.Text,
    'timeAtDomicile' : Minutes,
    'address' : IDL.Text,
  });
  const ServiceInput = IDL.Record({
    'kmStart' : Kilometers,
    'domicilios' : IDL.Vec(Domicilio),
    'waitMinutes' : Minutes,
    'officialName' : IDL.Text,
    'tagCount' : IDL.Nat,
    'kmEnd' : Kilometers,
  });
  const Pesos = IDL.Nat;
  const ServiceBreakdown = IDL.Record({
    'total' : Pesos,
    'kilometros' : Kilometers,
    'minutos' : Minutes,
    'importeTag' : Pesos,
    'cantidadTag' : IDL.Nat,
    'bajadaDeBandera' : Pesos,
    'importeKilometros' : Pesos,
    'importeTiempo' : Pesos,
  });
  const MobileInput = IDL.Record({
    'serviceType' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'officialName' : IDL.Text,
    'mobileIdentifier' : IDL.Text,
  });
  const MobileStatus = IDL.Variant({
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const MobileView = IDL.Record({
    'id' : MobileId,
    'status' : MobileStatus,
    'serviceType' : IDL.Text,
    'username' : IDL.Text,
    'lastUpdate' : IDL.Opt(Timestamp),
    'officialName' : IDL.Text,
    'lastLatitude' : IDL.Opt(IDL.Float64),
    'lastLongitude' : IDL.Opt(IDL.Float64),
    'mobileIdentifier' : IDL.Text,
  });
  const ServiceId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const MobilePositionView = IDL.Record({
    'id' : MobileId,
    'status' : MobileStatus,
    'latitude' : IDL.Opt(IDL.Float64),
    'lastUpdate' : IDL.Opt(Timestamp),
    'officialName' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
    'mobileIdentifier' : IDL.Text,
  });
  const Rates = IDL.Record({
    'porMinuto' : Pesos,
    'porKilometro' : Pesos,
    'bajadaDeBandera' : Pesos,
    'porTag' : Pesos,
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'kmStart' : Kilometers,
    'total' : Pesos,
    'owner' : IDL.Principal,
    'breakdown' : ServiceBreakdown,
    'createdAt' : Timestamp,
    'domicilios' : IDL.Vec(Domicilio),
    'waitMinutes' : Minutes,
    'officialName' : IDL.Text,
    'kmTraveled' : Kilometers,
    'tagCount' : IDL.Nat,
    'kmEnd' : Kilometers,
  });
  const RouteFilter = IDL.Record({
    'to' : IDL.Opt(Timestamp),
    'from' : IDL.Opt(Timestamp),
    'mobileId' : IDL.Opt(MobileId),
  });
  const ServiceSummary = IDL.Record({
    'id' : ServiceId,
    'total' : Pesos,
    'createdAt' : Timestamp,
    'minutes' : Minutes,
    'officialName' : IDL.Text,
    'kmTraveled' : Kilometers,
  });
  const Position = IDL.Record({
    'latitude' : IDL.Float64,
    'recordedAt' : Timestamp,
    'longitude' : IDL.Float64,
  });
  const MobileUpdate = IDL.Record({
    'serviceType' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Opt(IDL.Text),
    'officialName' : IDL.Text,
    'mobileIdentifier' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRoute' : IDL.Func([RouteInput], [RouteView], []),
    'calculateService' : IDL.Func(
        [ServiceInput],
        [ServiceBreakdown],
        ['query'],
      ),
    'createMobile' : IDL.Func([MobileInput], [MobileView], []),
    'deleteMobile' : IDL.Func([MobileId], [], []),
    'deleteService' : IDL.Func([ServiceId], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerMobile' : IDL.Func([], [IDL.Opt(MobileView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMobile' : IDL.Func([MobileId], [IDL.Opt(MobileView)], ['query']),
    'getMobilePosition' : IDL.Func(
        [MobileId],
        [IDL.Opt(MobilePositionView)],
        ['query'],
      ),
    'getRates' : IDL.Func([], [Rates], ['query']),
    'getRoute' : IDL.Func([RouteId], [IDL.Opt(RouteView)], ['query']),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkMobilePrincipal' : IDL.Func([IDL.Text, IDL.Text], [MobileView], []),
    'listMobilePositions' : IDL.Func(
        [],
        [IDL.Vec(MobilePositionView)],
        ['query'],
      ),
    'listMobiles' : IDL.Func([], [IDL.Vec(MobileView)], ['query']),
    'listRoutes' : IDL.Func([RouteFilter], [IDL.Vec(RouteView)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(ServiceSummary)], ['query']),
    'registerPosition' : IDL.Func([IDL.Float64, IDL.Float64], [Position], []),
    'saveService' : IDL.Func([ServiceInput], [Service], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateMobile' : IDL.Func([MobileId, MobileUpdate], [MobileView], []),
    'updateRates' : IDL.Func([Rates], [Rates], []),
    'updateService' : IDL.Func([ServiceId, ServiceInput], [Service], []),
  });
};

export const init = ({ IDL }) => { return []; };