/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Domicilio {
  'arrivalTime' : string,
  'departureTime' : string,
  'timeAtDomicile' : Minutes,
  'address' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Kilometers = number;
export type Minutes = number;
export type MobileId = bigint;
export interface MobileInput {
  'serviceType' : string,
  'username' : string,
  'password' : string,
  'officialName' : string,
  'mobileIdentifier' : string,
}
export interface MobilePositionView {
  'id' : MobileId,
  'status' : MobileStatus,
  'latitude' : [] | [number],
  'lastUpdate' : [] | [Timestamp],
  'officialName' : string,
  'longitude' : [] | [number],
  'mobileIdentifier' : string,
}
export type MobileStatus = { 'offline' : null } |
  { 'online' : null };
export interface MobileUpdate {
  'serviceType' : string,
  'username' : string,
  'password' : [] | [string],
  'officialName' : string,
  'mobileIdentifier' : string,
}
export interface MobileView {
  'id' : MobileId,
  'status' : MobileStatus,
  'serviceType' : string,
  'username' : string,
  'lastUpdate' : [] | [Timestamp],
  'officialName' : string,
  'lastLatitude' : [] | [number],
  'lastLongitude' : [] | [number],
  'mobileIdentifier' : string,
}
export type Pesos = bigint;
export interface Position {
  'latitude' : number,
  'recordedAt' : Timestamp,
  'longitude' : number,
}
export interface Rates {
  'porMinuto' : Pesos,
  'porKilometro' : Pesos,
  'bajadaDeBandera' : Pesos,
  'porTag' : Pesos,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RouteFilter {
  'to' : [] | [Timestamp],
  'from' : [] | [Timestamp],
  'mobileId' : [] | [MobileId],
}
export type RouteId = bigint;
export interface RouteInput {
  'serviceType' : string,
  'mobileId' : MobileId,
  'officialName' : string,
}
export interface RouteView {
  'id' : RouteId,
  'serviceType' : string,
  'startedAt' : Timestamp,
  'endedAt' : [] | [Timestamp],
  'mobileId' : MobileId,
  'officialName' : string,
  'durationMinutes' : [] | [Minutes],
  'totalKilometers' : Kilometers,
}
export interface Service {
  'id' : ServiceId,
  'kmStart' : Kilometers,
  'total' : Pesos,
  'owner' : Principal,
  'breakdown' : ServiceBreakdown,
  'createdAt' : Timestamp,
  'domicilios' : Array<Domicilio>,
  'waitMinutes' : Minutes,
  'officialName' : string,
  'kmTraveled' : Kilometers,
  'tagCount' : bigint,
  'kmEnd' : Kilometers,
}
export interface ServiceBreakdown {
  'total' : Pesos,
  'kilometros' : Kilometers,
  'minutos' : Minutes,
  'importeTag' : Pesos,
  'cantidadTag' : bigint,
  'bajadaDeBandera' : Pesos,
  'importeKilometros' : Pesos,
  'importeTiempo' : Pesos,
}
export type ServiceId = bigint;
export interface ServiceInput {
  'kmStart' : Kilometers,
  'domicilios' : Array<Domicilio>,
  'waitMinutes' : Minutes,
  'officialName' : string,
  'tagCount' : bigint,
  'kmEnd' : Kilometers,
}
export interface ServiceSummary {
  'id' : ServiceId,
  'total' : Pesos,
  'createdAt' : Timestamp,
  'minutes' : Minutes,
  'officialName' : string,
  'kmTraveled' : Kilometers,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Asigna una ruta a un móvil (solo administrador).
   */
  'assignRoute' : ActorMethod<[RouteInput], RouteView>,
  /**
   * / Calcula el desglose de un servicio sin guardarlo (usuario firmado).
   */
  'calculateService' : ActorMethod<[ServiceInput], ServiceBreakdown>,
  /**
   * / Crea un móvil; rechaza el número 51 con error en español (solo administrador).
   */
  'createMobile' : ActorMethod<[MobileInput], MobileView>,
  /**
   * / Elimina un móvil existente (solo administrador).
   */
  'deleteMobile' : ActorMethod<[MobileId], undefined>,
  /**
   * / Elimina un servicio guardado (usuario firmado).
   */
  'deleteService' : ActorMethod<[ServiceId], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Devuelve la documentación Markdown de la API pública del backend.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Devuelve el móvil vinculado al llamador firmado, o null si no tiene ninguno.
   */
  'getCallerMobile' : ActorMethod<[], [] | [MobileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Obtiene un móvil por identificador (solo administrador).
   */
  'getMobile' : ActorMethod<[MobileId], [] | [MobileView]>,
  /**
   * / Detalle de la última posición de un móvil (solo administrador).
   */
  'getMobilePosition' : ActorMethod<[MobileId], [] | [MobilePositionView]>,
  /**
   * / Obtiene las tarifas vigentes (usuario firmado).
   */
  'getRates' : ActorMethod<[], Rates>,
  /**
   * / Detalle de una ruta (solo administrador).
   */
  'getRoute' : ActorMethod<[RouteId], [] | [RouteView]>,
  /**
   * / Detalle de un servicio guardado (usuario firmado).
   */
  'getService' : ActorMethod<[ServiceId], [] | [Service]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Vincula el principal del llamador al móvil con las credenciales indicadas (usuario firmado).
   */
  'linkMobilePrincipal' : ActorMethod<[string, string], MobileView>,
  /**
   * / Última posición conocida de cada móvil (solo administrador).
   */
  'listMobilePositions' : ActorMethod<[], Array<MobilePositionView>>,
  /**
   * / Lista los móviles (solo administrador).
   */
  'listMobiles' : ActorMethod<[], Array<MobileView>>,
  /**
   * / Consulta recorridos filtrados por móvil y rango de fechas (solo administrador).
   */
  'listRoutes' : ActorMethod<[RouteFilter], Array<RouteView>>,
  /**
   * / Lista los servicios guardados del usuario (usuario firmado).
   */
  'listServices' : ActorMethod<[], Array<ServiceSummary>>,
  /**
   * / Registra la posición GPS del móvil del usuario firmado.
   */
  'registerPosition' : ActorMethod<[number, number], Position>,
  /**
   * / Guarda un servicio calculado (usuario firmado).
   */
  'saveService' : ActorMethod<[ServiceInput], Service>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Edita un móvil existente (solo administrador).
   */
  'updateMobile' : ActorMethod<[MobileId, MobileUpdate], MobileView>,
  /**
   * / Actualiza las tarifas aplicadas a los cálculos siguientes (solo administrador).
   */
  'updateRates' : ActorMethod<[Rates], Rates>,
  /**
   * / Edita un servicio guardado (usuario firmado).
   */
  'updateService' : ActorMethod<[ServiceId, ServiceInput], Service>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];