/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface Domicilio {
    arrivalTime: string;
    departureTime: string;
    timeAtDomicile: Minutes;
    address: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type Kilometers = number;
export type Minutes = number;
export type MobileId = bigint;
export interface MobileInput {
    serviceType: string;
    username: string;
    password: string;
    officialName: string;
    mobileIdentifier: string;
}
export interface MobilePositionView {
    id: MobileId;
    status: MobileStatus;
    latitude?: number;
    lastUpdate?: Timestamp;
    officialName: string;
    longitude?: number;
    mobileIdentifier: string;
}
export interface MobileUpdate {
    serviceType: string;
    username: string;
    password?: string;
    officialName: string;
    mobileIdentifier: string;
}
export interface MobileView {
    id: MobileId;
    status: MobileStatus;
    serviceType: string;
    username: string;
    lastUpdate?: Timestamp;
    officialName: string;
    lastLatitude?: number;
    lastLongitude?: number;
    mobileIdentifier: string;
}
export type Pesos = bigint;
export interface Position {
    latitude: number;
    recordedAt: Timestamp;
    longitude: number;
}
export interface Rates {
    porMinuto: Pesos;
    porKilometro: Pesos;
    bajadaDeBandera: Pesos;
    porTag: Pesos;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface RouteFilter {
    to?: Timestamp;
    from?: Timestamp;
    mobileId?: MobileId;
}
export type RouteId = bigint;
export interface RouteInput {
    serviceType: string;
    mobileId: MobileId;
    officialName: string;
}
export interface RouteView {
    id: RouteId;
    serviceType: string;
    startedAt: Timestamp;
    endedAt?: Timestamp;
    mobileId: MobileId;
    officialName: string;
    durationMinutes?: Minutes;
    totalKilometers: Kilometers;
}
export interface Service {
    id: ServiceId;
    kmStart: Kilometers;
    total: Pesos;
    owner: Principal;
    breakdown: ServiceBreakdown;
    createdAt: Timestamp;
    domicilios: Array<Domicilio>;
    waitMinutes: Minutes;
    officialName: string;
    kmTraveled: Kilometers;
    tagCount: bigint;
    kmEnd: Kilometers;
}
export interface ServiceBreakdown {
    total: Pesos;
    kilometros: Kilometers;
    minutos: Minutes;
    importeTag: Pesos;
    cantidadTag: bigint;
    bajadaDeBandera: Pesos;
    importeKilometros: Pesos;
    importeTiempo: Pesos;
}
export type ServiceId = bigint;
export interface ServiceInput {
    kmStart: Kilometers;
    domicilios: Array<Domicilio>;
    waitMinutes: Minutes;
    officialName: string;
    tagCount: bigint;
    kmEnd: Kilometers;
}
export interface ServiceSummary {
    id: ServiceId;
    total: Pesos;
    createdAt: Timestamp;
    minutes: Minutes;
    officialName: string;
    kmTraveled: Kilometers;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum MobileStatus {
    offline = "offline",
    online = "online"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Asigna una ruta a un móvil (solo administrador).
     */
    assignRoute(input: RouteInput): Promise<RouteView>;
    /**
     * / Calcula el desglose de un servicio sin guardarlo (usuario firmado).
     */
    calculateService(input: ServiceInput): Promise<ServiceBreakdown>;
    /**
     * / Crea un móvil; rechaza el número 51 con error en español (solo administrador).
     */
    createMobile(input: MobileInput): Promise<MobileView>;
    /**
     * / Elimina un móvil existente (solo administrador).
     */
    deleteMobile(id: MobileId): Promise<void>;
    /**
     * / Elimina un servicio guardado (usuario firmado).
     */
    deleteService(id: ServiceId): Promise<void>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Devuelve la documentación Markdown de la API pública del backend.
     */
    getApiDoc(): Promise<string>;
    /**
     * / Devuelve el móvil vinculado al llamador firmado, o null si no tiene ninguno.
     */
    getCallerMobile(): Promise<MobileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Obtiene un móvil por identificador (solo administrador).
     */
    getMobile(id: MobileId): Promise<MobileView | null>;
    /**
     * / Detalle de la última posición de un móvil (solo administrador).
     */
    getMobilePosition(id: MobileId): Promise<MobilePositionView | null>;
    /**
     * / Obtiene las tarifas vigentes (usuario firmado).
     */
    getRates(): Promise<Rates>;
    /**
     * / Detalle de una ruta (solo administrador).
     */
    getRoute(id: RouteId): Promise<RouteView | null>;
    /**
     * / Detalle de un servicio guardado (usuario firmado).
     */
    getService(id: ServiceId): Promise<Service | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Vincula el principal del llamador al móvil con las credenciales indicadas (usuario firmado).
     */
    linkMobilePrincipal(username: string, password: string): Promise<MobileView>;
    /**
     * / Última posición conocida de cada móvil (solo administrador).
     */
    listMobilePositions(): Promise<Array<MobilePositionView>>;
    /**
     * / Lista los móviles (solo administrador).
     */
    listMobiles(): Promise<Array<MobileView>>;
    /**
     * / Consulta recorridos filtrados por móvil y rango de fechas (solo administrador).
     */
    listRoutes(filter: RouteFilter): Promise<Array<RouteView>>;
    /**
     * / Lista los servicios guardados del usuario (usuario firmado).
     */
    listServices(): Promise<Array<ServiceSummary>>;
    /**
     * / Registra la posición GPS del móvil del usuario firmado.
     */
    registerPosition(latitude: number, longitude: number): Promise<Position>;
    /**
     * / Guarda un servicio calculado (usuario firmado).
     */
    saveService(input: ServiceInput): Promise<Service>;
    schema(): Promise<string>;
    /**
     * / Edita un móvil existente (solo administrador).
     */
    updateMobile(id: MobileId, input: MobileUpdate): Promise<MobileView>;
    /**
     * / Actualiza las tarifas aplicadas a los cálculos siguientes (solo administrador).
     */
    updateRates(input: Rates): Promise<Rates>;
    /**
     * / Edita un servicio guardado (usuario firmado).
     */
    updateService(id: ServiceId, input: ServiceInput): Promise<Service>;
}
import type { Cell as _Cell, Error as _Error, Kilometers as _Kilometers, Minutes as _Minutes, MobileId as _MobileId, MobilePositionView as _MobilePositionView, MobileStatus as _MobileStatus, MobileUpdate as _MobileUpdate, MobileView as _MobileView, Result as _Result, Result__1 as _Result__1, RouteFilter as _RouteFilter, RouteId as _RouteId, RouteView as _RouteView, Service as _Service, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRoute(arg0: RouteInput): Promise<RouteView> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRoute(arg0);
                return from_candid_RouteView_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRoute(arg0);
            return from_candid_RouteView_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async calculateService(arg0: ServiceInput): Promise<ServiceBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateService(arg0);
            return result;
        }
    }
    async createMobile(arg0: MobileInput): Promise<MobileView> {
        if (this.processError) {
            try {
                const result = await this.actor.createMobile(arg0);
                return from_candid_MobileView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMobile(arg0);
            return from_candid_MobileView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMobile(arg0: MobileId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMobile(arg0);
            return result;
        }
    }
    async deleteService(arg0: ServiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerMobile(): Promise<MobileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMobile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMobile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMobile(arg0: MobileId): Promise<MobileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMobile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMobile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMobilePosition(arg0: MobileId): Promise<MobilePositionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMobilePosition(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMobilePosition(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRates(): Promise<Rates> {
        if (this.processError) {
            try {
                const result = await this.actor.getRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRates();
            return result;
        }
    }
    async getRoute(arg0: RouteId): Promise<RouteView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoute(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoute(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkMobilePrincipal(arg0: string, arg1: string): Promise<MobileView> {
        if (this.processError) {
            try {
                const result = await this.actor.linkMobilePrincipal(arg0, arg1);
                return from_candid_MobileView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkMobilePrincipal(arg0, arg1);
            return from_candid_MobileView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMobilePositions(): Promise<Array<MobilePositionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMobilePositions();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMobilePositions();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMobiles(): Promise<Array<MobileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMobiles();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMobiles();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRoutes(arg0: RouteFilter): Promise<Array<RouteView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRoutes(to_candid_RouteFilter_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRoutes(to_candid_RouteFilter_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(): Promise<Array<ServiceSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return result;
        }
    }
    async registerPosition(arg0: number, arg1: number): Promise<Position> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPosition(arg0, arg1);
            return result;
        }
    }
    async saveService(arg0: ServiceInput): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.saveService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveService(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateMobile(arg0: MobileId, arg1: MobileUpdate): Promise<MobileView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMobile(arg0, to_candid_MobileUpdate_n34(this._uploadFile, this._downloadFile, arg1));
                return from_candid_MobileView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMobile(arg0, to_candid_MobileUpdate_n34(this._uploadFile, this._downloadFile, arg1));
            return from_candid_MobileView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRates(arg0: Rates): Promise<Rates> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRates(arg0);
            return result;
        }
    }
    async updateService(arg0: ServiceId, arg1: ServiceInput): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Cell_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_MobilePositionView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MobilePositionView): MobilePositionView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MobileStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MobileStatus): MobileStatus {
    return "offline" in value ? MobileStatus.offline : "online" in value ? MobileStatus.online : value;
}
function from_candid_MobileView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MobileView): MobileView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RouteView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RouteView): RouteView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MobileView]): MobileView | null {
    return value.length === 0 ? null : from_candid_MobileView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MobilePositionView]): MobilePositionView | null {
    return value.length === 0 ? null : from_candid_MobilePositionView_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RouteView]): RouteView | null {
    return value.length === 0 ? null : from_candid_RouteView_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Minutes]): Minutes | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MobileId;
    status: _MobileStatus;
    serviceType: string;
    username: string;
    lastUpdate: [] | [_Timestamp];
    officialName: string;
    lastLatitude: [] | [number];
    lastLongitude: [] | [number];
    mobileIdentifier: string;
}): {
    id: MobileId;
    status: MobileStatus;
    serviceType: string;
    username: string;
    lastUpdate?: Timestamp;
    officialName: string;
    lastLatitude?: number;
    lastLongitude?: number;
    mobileIdentifier: string;
} {
    return {
        id: value.id,
        status: from_candid_MobileStatus_n12(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        username: value.username,
        lastUpdate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lastUpdate)),
        officialName: value.officialName,
        lastLatitude: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastLatitude)),
        lastLongitude: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastLongitude)),
        mobileIdentifier: value.mobileIdentifier
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n16(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n20(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MobileId;
    status: _MobileStatus;
    latitude: [] | [number];
    lastUpdate: [] | [_Timestamp];
    officialName: string;
    longitude: [] | [number];
    mobileIdentifier: string;
}): {
    id: MobileId;
    status: MobileStatus;
    latitude?: number;
    lastUpdate?: Timestamp;
    officialName: string;
    longitude?: number;
    mobileIdentifier: string;
} {
    return {
        id: value.id,
        status: from_candid_MobileStatus_n12(_uploadFile, _downloadFile, value.status),
        latitude: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.latitude)),
        lastUpdate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lastUpdate)),
        officialName: value.officialName,
        longitude: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.longitude)),
        mobileIdentifier: value.mobileIdentifier
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RouteId;
    serviceType: string;
    startedAt: _Timestamp;
    endedAt: [] | [_Timestamp];
    mobileId: _MobileId;
    officialName: string;
    durationMinutes: [] | [_Minutes];
    totalKilometers: _Kilometers;
}): {
    id: RouteId;
    serviceType: string;
    startedAt: Timestamp;
    endedAt?: Timestamp;
    mobileId: MobileId;
    officialName: string;
    durationMinutes?: Minutes;
    totalKilometers: Kilometers;
} {
    return {
        id: value.id,
        serviceType: value.serviceType,
        startedAt: value.startedAt,
        endedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.endedAt)),
        mobileId: value.mobileId,
        officialName: value.officialName,
        durationMinutes: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.durationMinutes)),
        totalKilometers: value.totalKilometers
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MobilePositionView>): Array<MobilePositionView> {
    return value.map((x)=>from_candid_MobilePositionView_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MobileView>): Array<MobileView> {
    return value.map((x)=>from_candid_MobileView_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RouteView>): Array<RouteView> {
    return value.map((x)=>from_candid_RouteView_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MobileUpdate_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MobileUpdate): _MobileUpdate {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_RouteFilter_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RouteFilter): _RouteFilter {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to?: Timestamp;
    from?: Timestamp;
    mobileId?: MobileId;
}): {
    to: [] | [_Timestamp];
    from: [] | [_Timestamp];
    mobileId: [] | [_MobileId];
} {
    return {
        to: value.to ? candid_some(value.to) : candid_none(),
        from: value.from ? candid_some(value.from) : candid_none(),
        mobileId: value.mobileId ? candid_some(value.mobileId) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: string;
    username: string;
    password?: string;
    officialName: string;
    mobileIdentifier: string;
}): {
    serviceType: string;
    username: string;
    password: [] | [string];
    officialName: string;
    mobileIdentifier: string;
} {
    return {
        serviceType: value.serviceType,
        username: value.username,
        password: value.password ? candid_some(value.password) : candid_none(),
        officialName: value.officialName,
        mobileIdentifier: value.mobileIdentifier
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
